title: Emma Krentz # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  data scientist, rock climber, jeopardy! enthusiast
  <br><br>
  <a href="https://www.linkedin.com/in/emma-krentz/">LinkedIn</a> 
  <br>
  <a href="https://github.com/emmakrentz/">GitHub</a> 
  <br>
  <a href="https://emma-k.medium.com/">Medium</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

      <!-- Show static HTML/CSS as a placeholder in case js is not enabled - javascript include will override this if things work -->
      <style type="text/css" media="screen">
  .gr_custom_container_1693489711 {
    /* customize your Goodreads widget container here*/
    border: 1px solid gray;
    border-radius:10px;
    padding: 10px 5px 10px 5px;
    background-color: transparent;
    color: #000000;
    width: 300px
  }
  .gr_custom_header_1693489711 {
    /* customize your Goodreads header here*/
    border-bottom: 1px solid gray;
    width: 100%;
    margin-bottom: 5px;
    text-align: center;
    font-size: 80%
  }
  .gr_custom_each_container_1693489711 {
    /* customize each individual book container here */
    width: 100%;
    clear: both;
    margin-bottom: 10px;
    overflow: auto;
    padding-bottom: 4px;
    border-bottom: 1px solid #aaa;
  }
  .gr_custom_book_container_1693489711 {
    /* customize your book covers here */
    overflow: hidden;
    height: 60px;
      float: left;
      margin-right: 4px;
      width: 39px;
  }
  .gr_custom_author_1693489711 {
    /* customize your author names here */
    font-size: 10px;
  }
  .gr_custom_tags_1693489711 {
    /* customize your tags here */
    font-size: 10px;
    color: gray;
  }
  .gr_custom_rating_1693489711 {
    /* customize your rating stars here */
    float: right;
  }
</style>

      <div id="gr_custom_widget_1693489711">
          <div class="gr_custom_container_1693489711">
    <h2 class="gr_custom_header_1693489711">
    <a style="text-decoration: none;" rel="nofollow" href="https://www.goodreads.com/review/list/107952595-emma-krentz?shelf=read&amp;utm_medium=api&amp;utm_source=custom_widget">Recently Read</a>
    </h2>
      <div class="gr_custom_each_container_1693489711">
          <div class="gr_custom_book_container_1693489711">
            <a title="Computing Taste: Algorithms and the Makers of Music Recommendation" rel="nofollow" href="https://www.goodreads.com/review/show/5809472988?utm_medium=api&amp;utm_source=custom_widget"><img alt="Computing Taste: Algorithms and the Makers of Music Recommendation" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1662567568l/60557009._SY75_.jpg" /></a>
          </div>
          <div class="gr_custom_title_1693489711">
            <a rel="nofollow" href="https://www.goodreads.com/review/show/5809472988?utm_medium=api&amp;utm_source=custom_widget">Computing Taste: Algorithms and the Makers of Music Recommendation</a>
          </div>
          <div class="gr_custom_author_1693489711">
            by <a rel="nofollow" href="https://www.goodreads.com/author/show/8585153.Nick_Seaver">Nick Seaver</a>
          </div>
      </div>
      <div class="gr_custom_each_container_1693489711">
          <div class="gr_custom_book_container_1693489711">
            <a title="Algorithms of Oppression: How Search Engines Reinforce Racism" rel="nofollow" href="https://www.goodreads.com/review/show/5809472311?utm_medium=api&amp;utm_source=custom_widget"><img alt="Algorithms of Oppression: How Search Engines Reinforce Racism" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1492944248l/34762552._SX50_.jpg" /></a>
          </div>
          <div class="gr_custom_title_1693489711">
            <a rel="nofollow" href="https://www.goodreads.com/review/show/5809472311?utm_medium=api&amp;utm_source=custom_widget">Algorithms of Oppression: How Search Engines Reinforce Racism</a>
          </div>
          <div class="gr_custom_author_1693489711">
            by <a rel="nofollow" href="https://www.goodreads.com/author/show/14532650.Safiya_Umoja_Noble">Safiya Umoja Noble</a>
          </div>
      </div>
      <div class="gr_custom_each_container_1693489711">
          <div class="gr_custom_book_container_1693489711">
            <a title="Discriminating Data: Correlation, Neighborhoods, and the New Politics of Recognition" rel="nofollow" href="https://www.goodreads.com/review/show/5809471145?utm_medium=api&amp;utm_source=custom_widget"><img alt="Discriminating Data: Correlation, Neighborhoods, and the New Politics of Recognition" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629820662l/56987196._SX50_.jpg" /></a>
          </div>
          <div class="gr_custom_title_1693489711">
            <a rel="nofollow" href="https://www.goodreads.com/review/show/5809471145?utm_medium=api&amp;utm_source=custom_widget">Discriminating Data: Correlation, Neighborhoods, and the New Politics of Recognition</a>
          </div>
          <div class="gr_custom_author_1693489711">
            by <a rel="nofollow" href="https://www.goodreads.com/author/show/767004.Wendy_Hui_Kyong_Chun">Wendy Hui Kyong Chun</a>
          </div>
      </div>
      <div class="gr_custom_each_container_1693489711">
          <div class="gr_custom_book_container_1693489711">
            <a title="Recommendation Engines (The MIT Press Essential Knowledge series)" rel="nofollow" href="https://www.goodreads.com/review/show/5809469328?utm_medium=api&amp;utm_source=custom_widget"><img alt="Recommendation Engines" border="0" src="https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1590444389l/51456662._SX50_.jpg" /></a>
          </div>
          <div class="gr_custom_title_1693489711">
            <a rel="nofollow" href="https://www.goodreads.com/review/show/5809469328?utm_medium=api&amp;utm_source=custom_widget">Recommendation Engines</a>
          </div>
          <div class="gr_custom_author_1693489711">
            by <a rel="nofollow" href="https://www.goodreads.com/author/show/531942.Michael_Schrage">Michael Schrage</a>
          </div>
      </div>
  <br style="clear: both"/>
  <center>
    <a rel="nofollow" href="https://www.goodreads.com/"><img alt="goodreads.com" style="border:0" src="https://s.gr-assets.com/images/widget/widget_logo.gif" /></a>
  </center>
  <noscript>
    Share <a rel="nofollow" href="https://www.goodreads.com/">book reviews</a> and ratings with Emma, and even join a <a rel="nofollow" href="https://www.goodreads.com/group">book club</a> on Goodreads.
  </noscript>
  </div>

      </div>
      <script src="https://www.goodreads.com/review/custom_widget/107952595.Recently%20Read?cover_position=left&cover_size=small&num_books=4&order=d&shelf=read&show_author=1&show_cover=1&show_rating=0&show_review=0&show_tags=0&show_title=1&sort=date_added&widget_bg_color=FFFFFF&widget_bg_transparent=true&widget_border_width=1&widget_id=1693489711&widget_text_color=000000&widget_title_size=small&widget_width=medium" type="text/javascript" charset="utf-8"></script>
